apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: replay/argo-events-role-binding-replay
  name: argo-events-role-binding-replay
  namespace: replay
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|replay|argo-events-role-binding-replay'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-role-replay
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo-events
