apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata: # kpt-merge: replay/default
  name: default
  namespace: replay
  annotations:
    internal.kpt.dev/upstream-identifier: 'argoproj.io|EventBus|replay|default'
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: token
