apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: argo-events/argo-events-sa
  name: argo-events-sa
  namespace: argo-events
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|argo-events|argo-events-sa'
