apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata: # kpt-merge: replay/k8s-trigger
  name: k8s-trigger
  namespace: replay
  annotations:
    internal.kpt.dev/upstream-identifier: 'argoproj.io|Sensor|replay|k8s-trigger'
spec:
  template:
    serviceAccountName: k8s-resource-sa
  dependencies:
  - name: test-dep
    eventSourceName: webhook
    eventName: example
  triggers:
  - template:
      name: webhook-pod-trigger
      k8s:
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: hello-world-
            spec:
              containers:
              - name: hello-container
                args:
                - "hello-world"
                command:
                - cowsay
                image: "docker/whalesay:latest"
        parameters:
        - src:
            dependencyName: test-dep
          dest: spec.containers.0.args.0
