apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata: # kpt-merge: /replay-trigger
  name: replay-trigger
  annotations:
    internal.kpt.dev/upstream-identifier: 'eventing.knative.dev|Trigger|default|replay-trigger'
spec:
  broker: default
  filter:
    attributes:
      type: com.video.replay.requested
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: replay-service
      namespace: replay
